### ISSUE TITLE
封面不一样

### ISSUE THREAD

**Issue by ranxuebin** [yuhlzu/LZUThesis2020#1]
# RT

**Comment by yuhlzu** [comment]
具体哪个地方不一样？

**Comment by VealM** [comment]
如果和萃英的模板封面一样，可以考虑这个[模板](https://github.com/VealM/LZUthesis2020)。听说数学院的封面与物理和萃英的模板都不一样....

**Comment by yuhlzu** [comment]
> 如果和萃英的模板封面一样，可以考虑这个[模板](https://github.com/VealM/LZUthesis2020)。听说数学院的封面与物理和萃英的模板都不一样....

 你的这个封面是2020草拟稿的要求，我这个模板里LZUThesis.cls这个文件是采用的这个标准，但是大多学院还是用的2007的标准，所以前几天我又做了LZUThesis2007.cls这个模板，也在这个项目里

**Comment by VealM** [comment]
> > 如果和萃英的模板封面一样，可以考虑这个[模板](https://github.com/VealM/LZUthesis2020)。听说数学院的封面与物理和萃英的模板都不一样....
> 
> 你的这个封面是2020草拟稿的要求，我这个模板里LZUThesis.cls这个文件是采用的这个标准，但是大多学院还是用的2007的标准，所以前几天我又做了LZUThesis2007.cls这个模板，也在这个项目里

头秃的是我们教秘只在四月初发过草拟稿并强调一定要看，如果没看你的repo我都没发现教务处文件的存在...教务处的发布时间是今年2月份，四月底是最后更新的时间么？

**Comment by yuhlzu** [comment]
> > > 如果和萃英的模板封面一样，可以考虑这个[模板](https://github.com/VealM/LZUthesis2020)。听说数学院的封面与物理和萃英的模板都不一样....
> > 
> > 
> > 你的这个封面是2020草拟稿的要求，我这个模板里LZUThesis.cls这个文件是采用的这个标准，但是大多学院还是用的2007的标准，所以前几天我又做了LZUThesis2007.cls这个模板，也在这个项目里
> 
> 头秃的是我们教秘只在四月初发过草拟稿并强调一定要看，如果没看你的repo我都没发现教务处文件的存在...教务处的发布时间是今年2月份，四月底是最后更新的时间么？

四月底教务处只是补充了2月的那个通知，模板还是2月发的那个2007年的标准，我本来也是按照草拟稿做的模板（模板是LZUThesis.cls），后来又加上了LZUThesis2007.cls这个模板
