### ISSUE TITLE
Plz add some items in title page

### ISSUE THREAD

**Issue by JChrysanthemum** [yuhlzu/LZUThesis2020#4]
你好 !

我是本部信息科學學院研究生！非常高興看到這個論文的latex項目，但是我是latex新手，並不清楚如何增添内容。

碩博的論文封皮需要額外添加“學校代碼”，“密級”和“分類號”，但我不知道如何去做。

如果有人會做，請告知，謝謝

![图片](https://user-images.githubusercontent.com/23024457/96875611-f9ecb400-14a9-11eb-9fc5-3dd0be1f82a1.png)

**Comment by JChrysanthemum** [comment]
我自己改了一个，https://github.com/JChrysanthemum/LZUThesis2020-PgD-PhD，没事了

**Comment by fengyongkang** [comment]
您好，我是2021年核学院毕业生，不知道毕业论文参考文献能否加入超链接，找了很多办法，找不到怎么去加。
